name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs: 
  lint:
    name: Lint with ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Run ESLint
        run: npx eslint .

  validate-html:
    name: Validate HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install jq
        run: sudo apt-get install -y jq
      - name: Validate HTML files using W3C API
        run: |
          for file in $(find . -name "*.html"); do
            echo "Validating $file"
            curl -s -F "file=@$file;type=text/html" https://validator.w3.org/nu/?out=json | \
            jq -e '.messages | length == 0' && echo "✅ $file is valid" || (echo "❌ $file has errors" && exit 1)
          done
          
  validate-css:
    name: Validate CSS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install jq
        run: sudo apt-get install -y jq
      - name: Validate CSS files using W3C API
        run: |
          for file in $(find . -name "*.css"); do
            echo "Validating $file"
            curl -s -F "file=@$file;type=text/css" https://jigsaw.w3.org/css-validator/validator?output=soap12 | \
            grep -q "<m:errorcount>0</m:errorcount>" && echo "✅ $file is valid" || (echo "❌ $file has errors" && exit 1)
          done

  tests:
    name: Unit Tests with Jest
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Run all tests
        run: npm test