name: CI Pipeline

on:
  pull_request:
  push:
    branches:
      - main

jobs: 
  lint:
    name: Lint with ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Run ESLint
        run: npx eslint .

  tests:
    name: Unit Tests with Jest
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Run all tests
        run: npm test