name: HTML and CSS Validation

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate-html:
    name: Validate HTML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate HTML files using W3C API
        run: |
          for file in $(find . -name "*.html"); do
            echo "Validating $file"
            curl -s -F "file=@$file;type=text/html" https://validator.w3.org/nu/?out=json | \
            jq -e '.messages | length == 0' && echo "✅ $file is valid" || (echo "❌ $file has errors" && exit 1)
          done
          
  validate-css:
    name: Validate CSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install curl and jq
        run: sudo apt-get install -y curl jq

      - name: Validate CSS files using W3C API
        run: |
          for file in $(find . -name "*.css"); do
            echo "Validating $file"
            curl -s -F "file=@$file;type=text/css" https://jigsaw.w3.org/css-validator/validator?output=soap12 | \
            grep -q "<m:errorcount>0</m:errorcount>" && echo "✅ $file is valid" || (echo "❌ $file has errors" && exit 1)
          done
